### ISSUE TITLE
lab2 - dozer endpoint in exercise project

### ISSUE THREAD

**Issue by jeichler** [gpe-mw-training/fuse-mapper-labs#2]
Is it an option to adjust the lab2-instructions in favor of letting the students create the complete route on their own?
If so, you could remove (or i can provide a proper PR for that) the camel/blueprint-context.xml from the exercise-lab2-project and the student has to get his hands on all needed deliverables.
Another plus: One has to check camels dozer endpoint documentation :-)

**Comment by nandanj** [comment]
The intent of this course is to give the student a feel for the GUI mapper tool. The Fuse integration course is really intended to be the route building lab. 

For the xml2json exercise, the (simple) route is provided out of the box and the student just has to build out the mapping (transformation.xml) using the UI.

**Comment by jeichler** [comment]
Makes sense, but then at least the transformation.xml and the test should be removed from the exercise project. Sending a PR tomorrow if that's fine for you (already have one which I closed prior to creating this ticket, just needs a little modification and should be good to go then).

**Comment by nandanj** [comment]
Go for it.

**Comment by jeichler** [comment]
https://github.com/gpe-mw-training/fuse-mapper-labs/pull/3
